# Generated by Django 5.2.4 on 2025-12-01 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPilot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='email',
            field=models.EmailField(default='exit', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='JobPilot.createjob'),
        ),
    ]
