# Generated by Django 5.2.4 on 2025-11-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPilot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reason_for_applying', models.TextField()),
                ('country_of_residence', models.CharField(max_length=200)),
                ('resume_upload', models.ImageField(blank=True, null=True, upload_to='CV/')),
                ('portfolio_link', models.URLField(max_length=355)),
            ],
        ),
    ]
